### ISSUE TITLE
ALOps SaaS Get Extensions / Publish Extension

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#116]
Hi,
is it possible to use basic authentication instead of OAuth2 because of the MultiFactorAuthentication issues not solved right now by microsoft? Switch of MFA is also not an option because of this warning message always showing up and deny access without using a GUI.
Regards

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport ,
Yess this is possible! We redesigned the API interface in ALOps for this based on the feedback we got from the last WebCast. Please be patient for a couple of days, we should be able to release the new task this week. We already have successful test on deploying apps to BC SaaS using the WebserviceAccessKey.

We'll report status on this issue as soon as the release is available!

Kind regards,

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport ,

Fix for this is in version v1.429, which we just released. Please note we replaced both the ALOpsSaaS tasks with one new task:  ALOpsExtensionAPI. Setup is similar and allows for all types of authentication. For SaaS you can use the BC-Username and a WebserviceAccessKey instead of OAuth.

Get Extensions:
```yaml
- task: ALOpsExtensionAPI@1
  displayName: 'Get Extensions - Azure Basic WebserviceAccessKey'
  inputs:
    api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/Sandbox/api'
    authentication: basic
    azure_tenant_id: '$(azure_tenant_id)'
    username: '$(bc_ws_user)'
    password: '$(bc_ws_pass)'
```

Publish Extension:
```yaml
- task: ALOpsExtensionAPI@1
  displayName: 'Publish Extensions - Azure Basic WebserviceAccessKey'
  inputs:
    interaction: publish
    api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/Sandbox/api'
    authentication: basic
    azure_tenant_id: '$(azure_tenant_id)'
    username: '$(bc_user)'
    password: '$(bc_password)'
    artifact_filter: '*.app'
```

Could you please validate the solution?

Kind regards,

**Comment by gintuoklis** [comment]
Hey @AdminHodor, 
Do you think I could use ALOpsExtensionAPI for onprem deployments too?
OnPrem has automation APIs as well (at least BC14 Spring 2019 edition)
![image](https://user-images.githubusercontent.com/16342128/80706136-10601700-8ae8-11ea-851d-5d81f343c4a7.png)

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

>>Do you think I could use ALOpsExtensionAPI for onprem deployments too?
Yess! It also works for on-premise, or any non-SaaS installation, but not out of the box I'm afraid.
Not any BC installation/docker comes with the ability to use this API.
https://github.com/Microsoft/AL/issues/2310#issuecomment-411465438

On the bright side, we have made a solution for this that is easily to deploy and enables use of the Automation API for Extensions. Now we got the v1.429 release out of the way, we'll focus on releasing this new add-on called "ALOps External Deployer". We only need to finish the documentation and publish it, we expect to have it online very soon! Will keep you posted on this.

Kind regards,

Bart Bourgeois

**Comment by InnoNavSupport** [comment]
Hi,
it is still not working for me. Let me check, if I get something wrong.

We, as a partner use our own domain user mapped to our customers Business Central Environment.
I open the User Settings on Customer Site and generate a WebServiceKey for my user.
After that, I can use this User for DevOps to access the environment.

Something missing?
For me it seems to look like that I need a licenced customer user to get this running?

![image](https://user-images.githubusercontent.com/62563638/80945121-60422500-8deb-11ea-9953-da88c0636822.png)

![image](https://user-images.githubusercontent.com/62563638/80946133-a5ffed00-8ded-11ea-81f6-eda6d46a8f5b.png)

**Comment by waldo1001** [comment]
Hi, did you try it with a licensed customer user?

**Comment by waldo1001** [comment]
@InnoNavSupport , is this still an issue?
