### ISSUE TITLE
Tests fails with ALOpsAppTest

### ISSUE THREAD

**Issue by nicolassaleron** [HodorNV/ALOps#13]
Hello,

First of all, sorry for all this issues I am posting :)

I am running ALOpsAppTest against my test app. All the tests succeed when they are run on the web client with the test tool page.

However, they are all failing (except empty codeunits) when running with ALOpsAppTest.
There is also some strange errors and messages at the end. Finally, _PublishTestResults_ is unable to publish any result because the file TestResults.xml cannot be found.

Is there something I am doing wrong?

**This is my yaml task**

- task: ALOpsAppTest@1
  inputs:
    usedocker: true
    import_action: "Overwrite"
    import_testtoolkit: True
    testfilter: $(TestFilter)
    show_available_tests: true
  continueOnError: true    

**This is the console outputs:**

*** Run Available Tests
  Codeunit 70001 Test XXX Failure (8.324 seconds)
    Testfunction VerifyXXX Failure (0.677 seconds)
    Testfunction VerifyXXX Failure (0.17 seconds)
    Testfunction VerifyXXX Failure (0.063 seconds)
    Testfunction VerifyXXX Failure (0.053 seconds)
    Testfunction VerifyXXX Failure (0.076 seconds)
    Testfunction VerifyXXX Failure (0.27 seconds)
    Testfunction VerifyXXX Failure (0.173 seconds)
    Testfunction VerifyXXX Failure (0.11 seconds)
    Testfunction VerifyXXX Failure (0.106 seconds)
    Testfunction VerifyXXX Failure (0.127 seconds)
  Codeunit 70004 Test XXX Success (0.219 seconds)
  Codeunit 70005 Test XXX Success (0.219 seconds)
  Codeunit 70006 Test XXX Success (0.551 seconds)
  Codeunit 70007 Test XXX Success (0.328 seconds)
  Codeunit 70008 Test XXX Success (0.597 seconds)
  Codeunit 70009 Test XXX ERROR: Transaction was rolled back by the server.
Failure (6.54 seconds)
  Codeunit 70010 Test XXX Message : There is a dialog box open in another browser window. You must close that dialog box or sign out.
##[error]ClientSession in Error
##[section]Finishing: ALOpsAppTest

**Comment by AdminHodor** [comment]
>>Finally, PublishTestResults is unable to publish any result because the file TestResults.xml cannot be found.
Thanks for this, we noticed the "PublishTestResult" step in our example has the wrong version @1, this should be @2. We corrected the example, here is the correct template:

- task: PublishTestResults**@2**
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

Could you please retry with this, and check which results are returned so we can look into that.

**Comment by nicolassaleron** [comment]
I have updated the PublishTestResults to v2.
But it does not retrieve the TestResults.xml file when an error occurs in AlOpsAppTest task.

In fact, some of my tests pass now with ALOpsAppTest but it still crashes with something about a dialog box. With the web client, all the tests pass.
Have you any idea of the meaning of this message?

** Run Available Tests
  Codeunit 70001 XXX Success (9.115 seconds)
  Codeunit 70004 XXX Success (0.328 seconds)
  Codeunit 70005 XXX Success (0.219 seconds)
  Codeunit 70006 XXX ERROR: Transaction was rolled back by the server.
Failure (2.097 seconds)
  Codeunit 70007 XXX Message : There is a dialog box open in another browser window. You must close that dialog box or sign out.
##[error]ClientSession in Error
##[section]Finishing: Run Tests

**Comment by nicolassaleron** [comment]
I think the problem is related to Run-TestsInNavContainer as the tests succeeds when codeunits are run one by one. But sometimes fail when they are run together.

**Comment by waldo1001** [comment]
We are using the same (and only existing) trick that navcontainerhelper is using to run the tests .. but we are not using navcontainerhelper itself.  Though - if you have the same kind of errors with the "Run-TestsInNavContainer", then the problem is indeed related to that component.

It could be that the problem is isolated in your codeunit 70007 .. try to avoid dialog boxes in tests.. .  

May be you can try to exclude that codeunit and try again (testfilter: 70000..70006|70008..80000)?

the fact that you don't have results, might be because of that failing test-component.  We will look into catching these kind of errors.. .

Thanks for your feedback!

**Comment by nicolassaleron** [comment]
Actually, when I run codeunit 70007 separately it works. It also contains a MessageHandler to handle a dialog that opens a the end of the tested function.

Works fine when it is run from web client, works fine when run alone with Run-TestsInNavContainer.
But fails when run with other codeunits.

Might be side effect of a difference between how transactions works between the trick and testtool ?

I gonna keep my workaround for now, thanks for your help :)

**Comment by waldo1001** [comment]
Might be - as said, we are unfortunately dependent from the "trick" that Freddy did, I'm afraid. 

May be you can try to run only 70007 in the build pipeline - just as a test?  Should work .. ?

**Comment by waldo1001** [comment]
In any case - Microsoft is looking into a better way of facilitating this - and obviously, we will make sure the builds transition seemlessly in that case ;-)
